In [1]:
# Check the updates in the data storage is accurate

In [39]:
import polars as pl
from alpha_utils import get_bucket_name, get_profile_name
from s3io import S3IO
from datetime import datetime

In [47]:
# get the ticker data
ticker_table = "stock_tracker/tickers.parq"
ticker_queue_table = "stock_tracker/tickers_queue.parq"

In [48]:
# create the s3io object
s3io = S3IO(bucket=get_bucket_name(),
            profile=get_profile_name())

# get the ticker table and ticker queue
ticker_queue = s3io.s3_read_parquet(file_path=ticker_queue_table)
tickers = s3io.s3_read_parquet(file_path=ticker_table)

print(ticker_table)
print(ticker_queue)

stock_tracker/tickers.parq
shape: (1_868, 4)
┌────────┬────────────────────────────┬────────────┬─────────────────┐
│ Symbol ┆ Download_time              ┆ Downloaded ┆ Download_Failed │
│ ---    ┆ ---                        ┆ ---        ┆ ---             │
│ str    ┆ datetime[μs]               ┆ bool       ┆ bool            │
╞════════╪════════════════════════════╪════════════╪═════════════════╡
│ AG     ┆ 2025-01-30 07:40:40.700590 ┆ false      ┆ false           │
│ PSX    ┆ 2025-02-03 21:15:51.267626 ┆ false      ┆ false           │
│ HLX    ┆ 2025-02-03 21:15:51.267626 ┆ false      ┆ false           │
│ KRP    ┆ 2025-02-03 21:15:51.267626 ┆ false      ┆ false           │
│ XPRO   ┆ 2025-02-03 21:15:51.267626 ┆ false      ┆ false           │
│ …      ┆ …                          ┆ …          ┆ …               │
│ MTCH   ┆ null                       ┆ false      ┆ false           │
│ PDFS   ┆ null                       ┆ false      ┆ false           │
│ QXO    ┆ null                       ┆ false      ┆ false           │
│ IPDN   ┆ null                       ┆ false      ┆ false           │
│ CRM    ┆ null                       ┆ false      ┆ false           │
└────────┴────────────────────────────┴────────────┴─────────────────┘

In [49]:
# get the list of tickers where download is null
downloaded_tickers = ticker_queue.filter(pl.col("Download_time").is_null(),
                                         )["Symbol"].to_list()
downloaded_tickers
# ticker_queue.filter(pl.col("Download_time").is_null())
# check for any updated tickers
# tickers.filter(pl.col("is_current") == False)

['ACMR',
 'BL',
 'CRWD',
 'APP',
 'CSAI',
 'ADI',
 'LSCC',
 'RGTI',
 'DDD',
 'SSYS',
 'SST',
 'LOGI',
 'GMGI',
 'AWRE',
 'DSP',
 'SKYT',
 'VSAT',
 'CYCUW',
 'FIVN',
 'BSY',
 'SHLS',
 'DOCU',
 'MSPR',
 'CYN',
 'AUUD',
 'PLTR',
 'LDTCW',
 'CEVA',
 'VIAV',
 'KTCC',
 'DIOD',
 'HOLO',
 'WGS',
 'ADEA',
 'SNCR',
 'COHR',
 'BLIN',
 'PRO',
 'DUOT',
 'ICHR',
 'PL',
 'VRSN',
 'UPWK',
 'HOLOW',
 'AVNW',
 'PODC',
 'MOBX',
 'DV',
 'AIFF',
 'EA',
 'VERX',
 'GDDY',
 'RUM',
 'BOX',
 'RMBL',
 'BAND',
 'MKTW',
 'ASST',
 'BHE',
 'WGSWW',
 'AI',
 'AUUDW',
 'RPD',
 'SMSI',
 'DGLY',
 'CCSI',
 'ZS',
 'TXN',
 'LDOS',
 'TLS',
 'SNPS',
 'QLYS',
 'VICR',
 'IAS',
 'DXC',
 'VECO',
 'CFLT',
 'VRME',
 'DOMO',
 'PCOR',
 'VSH',
 'MEI',
 'QMCO',
 'HUYA',
 'VERI',
 'PDYNW',
 'FRSH',
 'TTD',
 'MYPS',
 'TTMI',
 'YEXT',
 'PDYN',
 'TZUP',
 'VRSK',
 'TWLO',
 'LAW',
 'UPLD',
 'VRMEW',
 'MLGO',
 'GWRE',
 'FDS',
 'XYZ',
 'BEEM',
 'APPN',
 'SPWRW',
 'RNG',
 'MSTR',
 'SITM',
 'OOMA',
 'ZETA',
 'AREN',
 'AUR',
 'UI',
 'VUZI',
 'DELL',
 'FORM',
 'APH',
 'S',
 'EVGOW',
 'UCTT',
 'CMTL',
 'OPXS',
 'WDAY',
 'JAMF',
 'MPTI',
 'TAIT',
 'WFCF',
 'DOCS',
 'BILL',
 'FSLR',
 'CREX',
 'AISPW',
 'ALOT',
 'IBM',
 'NABL',
 'FROG',
 'TACT',
 'RMBS',
 'IAC',
 'SLNH',
 'BLBX',
 'OSIS',
 'GDRX',
 'GTM',
 'RBBN',
 'BNAIW',
 'CRSR',
 'INDI',
 'HUBB',
 'XPER',
 'IDN',
 'ALAB',
 'AIRG',
 'KLTR',
 'FTNT',
 'DVLT',
 'FORA',
 'CCLD',
 'LRCX',
 'OSS',
 'SSTI',
 'WOLF',
 'SLAB',
 'QCOM',
 'KVHI',
 'CERT',
 'ORCL',
 'VPG',
 'SAIL',
 'SABR',
 'QUIK',
 'AMAT',
 'SPSC',
 'HPQ',
 'PINS',
 'ONDS',
 'MSAIW',
 'GLOB',
 'FATN',
 'DUOL',
 'POWI',
 'AMKR',
 'CVV',
 'TRAK',
 'IVDAW',
 'OLO',
 'DDOG',
 'SNAL',
 'HCAT',
 'WATT',
 'ALKT',
 'LASR',
 'CXM',
 'SNX',
 'NIXXW',
 'AMST',
 'APPF',
 'AUROW',
 'NSYS',
 'STRF',
 'SLNHP',
 'AMBA',
 'GOOG',
 'PATH',
 'EXFY',
 'ONTF',
 'WAY',
 'TOST',
 'SAIC',
 'XRX',
 'XTIA',
 'OB',
 'AVDX',
 'LPSN',
 'EVER',
 'YOU',
 'OLED',
 'IPWR',
 'GIGGU',
 'VRNT',
 'LTRYW',
 'TASK',
 'RBRK',
 'STRM',
 'BNZI',
 'MTSI',
 'PLAB',
 'MSI',
 'ALMU',
 'FNGR',
 'CETX',
 'NIXX',
 'NVTS',
 'CRCT',
 'MAPSW',
 'QTWO',
 'RELL',
 'ACLS',
 'KVYO',
 'PLUS',
 'PI',
 'ON',
 'CERS',
 'GEG',
 'CCRD',
 'IPGP',
 'FTCI',
 'INGM',
 'META',
 'CRWV',
 'CSGS',
 'ONFOW',
 'RBLX',
 'ADP',
 'TRUE',
 'CXAIW',
 'PEGA',
 'BKYI',
 'EB',
 'PENG',
 'QUBT',
 'RFIL',
 'OMCL',
 'OS',
 'CACI',
 'HPE',
 'MSPRW',
 'COUR',
 'HSTM',
 'AUID',
 'QRVO',
 'IOT',
 'NEE',
 'MSFT',
 'IDAI',
 'TRIP',
 'CRDO',
 'MPWR',
 'ZIP',
 'OBLG',
 'AEIS',
 'NRDS',
 'SCSC',
 'NTAP',
 'OPTX',
 'BRZE',
 'LGL',
 'PAYC',
 'AVGO',
 'ZSPC',
 'ASUR',
 'TYL',
 'ALRM',
 'JKHY',
 'RMSGW',
 'GE',
 'DAY',
 'MAPS',
 'MRVL',
 'LDTC',
 'AMD',
 'CARS',
 'SEMR',
 'GENVR',
 'ENS',
 'RMSG',
 'CDNS',
 'INOD',
 'MSPRZ',
 'AVPTW',
 'CNXC',
 'NTWK',
 'ONFO',
 'GEN',
 'DJT',
 'RDDT',
 'CSPI',
 'JBL',
 'TBRG',
 'DT',
 'COMP',
 'SGMA',
 'PXLW',
 'WEAV',
 'PRCH',
 'PRSO',
 'WK',
 'SSTK',
 'RGTIW',
 'MSAI',
 'NVDA',
 'RDVT',
 'GOOGL',
 'EVGO',
 'KIND',
 'SKLZ',
 'OPTXW',
 'ISSC',
 'KLAC',
 'SNOW',
 'AVT',
 'AZTA',
 'KD',
 'ANSS',
 'ZM',
 'WDC',
 'BIGC',
 'CVLT',
 'BMBL',
 'TDC',
 'MVIS',
 'FSLY',
 'MRCY',
 'LNW',
 'PLXS',
 'MITK',
 'BKTI',
 'BKSY',
 'PSTG',
 'IONQ',
 'AISP',
 'ESP',
 'VRAR',
 'TRT',
 'ENPH',
 'LTRY',
 'MCHP',
 'PSN',
 'ASYS',
 'CCLDO',
 'SANM',
 'AEYE',
 'ARW',
 'CYCU',
 'AIP',
 'INSE',
 'SMCI',
 'RXT',
 'SOUN',
 'EVCM',
 'ADSK',
 'BLKB',
 'MLNK',
 'EPAC',
 'TTWO',
 'HUBS',
 'DH',
 'NTCT',
 'MANH',
 'MQ',
 'VREX',
 'MARA',
 'TYGO',
 'TRNR',
 'GSIT',
 'MRIN',
 'INTU',
 'NOW',
 'WULF',
 'UMAC',
 'BBAI',
 'GXAI',
 'OTIS',
 'NET',
 'SSNC',
 'RUMBW',
 'ADBE',
 'LINK',
 'TEM',
 'ACIW',
 'CCCS',
 'EMR',
 'HLIT',
 'KULR',
 'CTSH',
 'GTLB',
 'SPT',
 'BNAI',
 'PTC',
 'RAMP',
 'KOPN',
 'GDYN',
 'UUU',
 'MXL',
 'GPUS',
 'TENB',
 'RAIN',
 'INTC',
 'FAAS',
 'VMEO',
 'SCKT',
 'EVLVW',
 'MU',
 'NTNX',
 'PRGS',
 'AAOI',
 'OSPN',
 'CARG',
 'LPTH',
 'CW',
 'ASAN',
 'DJTWW',
 'SMRT',
 'MDB',
 'SLP',
 'SYNA',
 'MOBXW',
 'NCNO',
 'TTAN',
 'WYY',
 'EGAN',
 'INVE',
 'AMPL',
 'BNZIW',
 'PCTY',
 'CXAI',
 'CWAN',
 'EPAM',
 'MRAM',
 'MYPSW',
 'SWKS',
 'VRT',
 'COMM',
 'MSGM',
 'SOUNW',
 'GCTS',
 'NVEC',
 'AXTI',
 'AAPL',
 'BASE',
 'INTA',
 'SPWR',
 'MCHPP',
 'CLMB',
 'DMRC',
 'PUBM',
 'VRNS',
 'ESTC',
 'CTS',
 'CRUS',
 'DTSTW',
 'GRYP',
 'ATHR',
 'SKIL',
 'GFS',
 'CRNC',
 'PANW',
 'IVDA',
 'INFA',
 'SVCO',
 'ETWO',
 'CDLX',
 'PD',
 'MGNI',
 'DOCN',
 'KE',
 'SNAP',
 'DTST',
 'SNDK',
 'UIS',
 'GEGGL',
 'AVPT',
 'RAINW',
 'VEEV',
 'BLND',
 'ULY',
 'RCAT',
 'U',
 'SOTK',
 'FAASW',
 'ALGM',
 'HCTI',
 'STRK',
 'LZ',
 'OKTA',
 'IMMR',
 'DBX',
 'AGYS',
 'ASTI',
 'EVLV',
 'ATOM',
 'BLZE',
 'MTCH',
 'PDFS',
 'QXO',
 'IPDN',
 'CRM']

In [28]:
# check for any duplicates
tickers.select(pl.col("Symbol")).to_series().value_counts().filter(pl.col("count") > 1)

shape: (0, 2)
┌────────┬───────┐
│ Symbol ┆ count │
│ ---    ┆ ---   │
│ str    ┆ u32   │
╞════════╪═══════╡
└────────┴───────┘

In [29]:
# print the duplicate symbols in the dataframe
duplicate_tickers = (tickers.select(pl.col("Symbol"))
                     .to_series().value_counts()
                     .filter(pl.col("count") > 1)
                     .select(pl.col("Symbol")).to_series())

tickers.filter(pl.col("Symbol").is_in(duplicate_tickers)).unique()

shape: (0, 10)
┌────────┬──────┬────────────┬─────────┬───┬──────────┬────────────┬────────────┬──────────────┐
│ Symbol ┆ Name ┆ Market Cap ┆ Country ┆ … ┆ Industry ┆ Market Cap ┆ is_current ┆ updated_time │
│ ---    ┆ ---  ┆ ---        ┆ ---     ┆   ┆ ---      ┆ Name       ┆ ---        ┆ ---          │
│ str    ┆ str  ┆ f64        ┆ str     ┆   ┆ str      ┆ ---        ┆ bool       ┆ datetime[μs] │
│        ┆      ┆            ┆         ┆   ┆          ┆ str        ┆            ┆              │
╞════════╪══════╪════════════╪═════════╪═══╪══════════╪════════════╪════════════╪══════════════╡
└────────┴──────┴────────────┴─────────┴───┴──────────┴────────────┴────────────┴──────────────┘

In [13]:
# drop duplicates and write back to s3
tickers_dropped = tickers.unique()

(tickers_dropped.select(pl.col("Symbol"))
                     .to_series().value_counts()
                     .filter(pl.col("count") > 1)
                     .select(pl.col("Symbol")).to_series())

shape: (0,)
Series: 'Symbol' [str]
[
]

In [14]:
s3io.s3_write_parquet(df=tickers_dropped, file_path=ticker_table)
print("written to s3")

written to s3

In [30]:
(ticker_queue.select(pl.col("Symbol"))
                     .to_series().value_counts()
                     .filter(pl.col("count") > 1)
                     .select(pl.col("Symbol")).to_series())

shape: (0,)
Series: 'Symbol' [str]
[
]

In [31]:
# check the number of symbols with what is in the ticker table
ticker_queue.select(pl.col("Symbol")).n_unique() == tickers_dropped.select(pl.col("Symbol")).n_unique()

True

In [32]:
downloaded_time = datetime(year=2025, month=1, day=28, hour=9, minute=11)
# set the download failed to false
ticker_queue_updated = ticker_queue.with_columns(
    Download_Failed=pl.when(pl.col("Downloaded") == False,
                            pl.col("Download_time") > downloaded_time).then(False).otherwise(pl.col("Download_Failed"))
)

ticker_queue_updated.filter(pl.col("Downloaded") == False,
                    pl.col("Download_Failed") == True,
                    pl.col("Download_time") > downloaded_time)

shape: (0, 4)
┌────────┬───────────────┬────────────┬─────────────────┐
│ Symbol ┆ Download_time ┆ Downloaded ┆ Download_Failed │
│ ---    ┆ ---           ┆ ---        ┆ ---             │
│ str    ┆ datetime[μs]  ┆ bool       ┆ bool            │
╞════════╪═══════════════╪════════════╪═════════════════╡
└────────┴───────────────┴────────────┴─────────────────┘

In [33]:
# write the que back to test the rerun
s3io.s3_write_parquet(df=ticker_queue_updated, file_path=ticker_queue_table)
print("written to s3")

written to s3

In [37]:
ticker_queue.filter(pl.col("Downloaded") == False,
                    pl.col("Download_Failed") == False)

shape: (26, 4)
┌────────┬────────────────────────────┬────────────┬─────────────────┐
│ Symbol ┆ Download_time              ┆ Downloaded ┆ Download_Failed │
│ ---    ┆ ---                        ┆ ---        ┆ ---             │
│ str    ┆ datetime[μs]               ┆ bool       ┆ bool            │
╞════════╪════════════════════════════╪════════════╪═════════════════╡
│ XOM    ┆ 2025-01-28 09:53:42.654783 ┆ false      ┆ false           │
│ CVX    ┆ 2025-01-28 09:53:42.654783 ┆ false      ┆ false           │
│ BE     ┆ 2025-01-28 09:53:42.654783 ┆ false      ┆ false           │
│ BPT    ┆ 2025-01-28 09:53:42.654783 ┆ false      ┆ false           │
│ AR     ┆ 2025-01-28 09:53:42.654783 ┆ false      ┆ false           │
│ …      ┆ …                          ┆ …          ┆ …               │
│ CRK    ┆ 2025-01-28 08:11:46.291942 ┆ false      ┆ false           │
│ SJT    ┆ 2025-01-28 08:11:46.291942 ┆ false      ┆ false           │
│ VAL    ┆ 2025-01-28 08:11:46.291942 ┆ false      ┆ false           │
│ SD     ┆ 2025-01-28 08:11:46.291942 ┆ false      ┆ false           │
│ PARR   ┆ 2025-01-28 08:11:46.291942 ┆ false      ┆ false           │
└────────┴────────────────────────────┴────────────┴─────────────────┘

In [7]:
tickers

shape: (395, 10)
┌────────┬────────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ Symbol ┆ Name       ┆ Market Cap ┆ Country   ┆ … ┆ Industry  ┆ Market    ┆ is_curren ┆ updated_t │
│ ---    ┆ ---        ┆ ---        ┆ ---       ┆   ┆ ---       ┆ Cap Name  ┆ t         ┆ ime       │
│ str    ┆ str        ┆ f64        ┆ str       ┆   ┆ str       ┆ ---       ┆ ---       ┆ ---       │
│        ┆            ┆            ┆           ┆   ┆           ┆ str       ┆ bool      ┆ datetime[ │
│        ┆            ┆            ┆           ┆   ┆           ┆           ┆           ┆ μs]       │
╞════════╪════════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ AACG   ┆ ATA        ┆ 2.6691308e ┆ China     ┆ … ┆ Other     ┆ Nano      ┆ true      ┆ null      │
│        ┆ Creativity ┆ 7          ┆           ┆   ┆ Consumer  ┆           ┆           ┆           │
│        ┆ Global     ┆            ┆           ┆   ┆ Services  ┆           ┆           ┆           │
│        ┆ American…  ┆            ┆           ┆   ┆           ┆           ┆           ┆           │
│ AAT    ┆ American   ┆ 1.3624e9   ┆ United    ┆ … ┆ Real      ┆ Small     ┆ true      ┆ null      │
│        ┆ Assets     ┆            ┆ States    ┆   ┆ Estate    ┆           ┆           ┆           │
│        ┆ Trust Inc. ┆            ┆           ┆   ┆ Investmen ┆           ┆           ┆           │
│        ┆ Com…       ┆            ┆           ┆   ┆ t Trusts  ┆           ┆           ┆           │
│ ABR    ┆ Arbor      ┆ 2.6037e9   ┆ United    ┆ … ┆ Real      ┆ Medium    ┆ true      ┆ null      │
│        ┆ Realty     ┆            ┆ States    ┆   ┆ Estate    ┆           ┆           ┆           │
│        ┆ Trust      ┆            ┆           ┆   ┆ Investmen ┆           ┆           ┆           │
│        ┆ Common     ┆            ┆           ┆   ┆ t Trusts  ┆           ┆           ┆           │
│        ┆ Stoc…      ┆            ┆           ┆   ┆           ┆           ┆           ┆           │
│ ACR    ┆ ACRES      ┆ 1.41546714 ┆ United    ┆ … ┆ Real      ┆ Micro     ┆ true      ┆ null      │
│        ┆ Commercial ┆ e8         ┆ States    ┆   ┆ Estate    ┆           ┆           ┆           │
│        ┆ Realty     ┆            ┆           ┆   ┆ Investmen ┆           ┆           ┆           │
│        ┆ Corp. …    ┆            ┆           ┆   ┆ t Trusts  ┆           ┆           ┆           │
│ ACRE   ┆ Ares       ┆ 3.2179885e ┆ United    ┆ … ┆ Real      ┆ Small     ┆ true      ┆ null      │
│        ┆ Commercial ┆ 8          ┆ States    ┆   ┆ Estate    ┆           ┆           ┆           │
│        ┆ Real       ┆            ┆           ┆   ┆ Investmen ┆           ┆           ┆           │
│        ┆ Estate Co… ┆            ┆           ┆   ┆ t Trusts  ┆           ┆           ┆           │
│ …      ┆ …          ┆ …          ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ WY     ┆ Weyerhaeus ┆ 2.1993e10  ┆ United    ┆ … ┆ Real      ┆ Large     ┆ true      ┆ null      │
│        ┆ er Company ┆            ┆ States    ┆   ┆ Estate    ┆           ┆           ┆           │
│        ┆ Common St… ┆            ┆           ┆   ┆ Investmen ┆           ┆           ┆           │
│        ┆            ┆            ┆           ┆   ┆ t Trusts  ┆           ┆           ┆           │
│ XOM    ┆ Exxon      ┆ 4.8733e11  ┆ United    ┆ … ┆ Integrate ┆ Mega      ┆ true      ┆ null      │
│        ┆ Mobil Corp ┆            ┆ States    ┆   ┆ d oil     ┆           ┆           ┆           │
│        ┆ oration    ┆            ┆           ┆   ┆ Companies ┆           ┆           ┆           │
│        ┆ Common…    ┆            ┆           ┆   ┆           ┆           ┆           ┆           │
│ XPRO   ┆ Expro      ┆ 1.6520e9   ┆ United    ┆ … ┆ Oilfield  ┆ Small     ┆ true      ┆ null      │
│        ┆ Group      ┆            ┆ States    ┆   ┆ Services/ ┆           ┆           ┆           │
│        ┆ Holdings   ┆            ┆           ┆   ┆ Equipment ┆           ┆           ┆           │
│        ┆ N.V. Comm… ┆            ┆           ┆   ┆           ┆           ┆           ┆           │
│ YQ     ┆ 17         ┆ 1.3867305e ┆ China     ┆ … ┆ Other     ┆ Nano      ┆ true      ┆ null      │
│        ┆ Education  ┆ 7          ┆           ┆   ┆ Consumer  ┆           ┆           ┆           │
│        ┆ &          ┆            ┆           ┆   ┆ Services  ┆           ┆           ┆           │
│        ┆ Technology ┆            ┆           ┆   ┆           ┆           ┆           ┆           │
│        ┆ Grou…      ┆            ┆           ┆   ┆           ┆           ┆           ┆           │
│ ZCMD   ┆ Zhongchao  ┆ 3.081798e6 ┆ China     ┆ … ┆ Other     ┆ Nano      ┆ true      ┆ null      │
│        ┆ Inc. Class ┆            ┆           ┆   ┆ Consumer  ┆           ┆           ┆           │
│        ┆ A Ordinar… ┆            ┆           ┆   ┆ Services  ┆           ┆           ┆           │
└────────┴────────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [41]:
df_consumer = pl.read_csv("data_backup/technology.csv")
df_consumer.head()

shape: (5, 11)
┌────────┬────────────┬───────────┬────────────┬───┬──────────┬──────────┬────────────┬────────────┐
│ Symbol ┆ Name       ┆ Last Sale ┆ Net Change ┆ … ┆ IPO Year ┆ Volume   ┆ Sector     ┆ Industry   │
│ ---    ┆ ---        ┆ ---       ┆ ---        ┆   ┆ ---      ┆ ---      ┆ ---        ┆ ---        │
│ str    ┆ str        ┆ str       ┆ f64        ┆   ┆ i64      ┆ i64      ┆ str        ┆ str        │
╞════════╪════════════╪═══════════╪════════════╪═══╪══════════╪══════════╪════════════╪════════════╡
│ AAOI   ┆ Applied    ┆ $16.83    ┆ 0.57       ┆ … ┆ 2013     ┆ 2508128  ┆ Technology ┆ Semiconduc │
│        ┆ Optoelectr ┆           ┆            ┆   ┆          ┆          ┆            ┆ tors       │
│        ┆ onics Inc. ┆           ┆            ┆   ┆          ┆          ┆            ┆            │
│        ┆ C…         ┆           ┆            ┆   ┆          ┆          ┆            ┆            │
│ AAPL   ┆ Apple Inc. ┆ $203.92   ┆ 3.29       ┆ … ┆ 1980     ┆ 46538043 ┆ Technology ┆ Computer   │
│        ┆ Common     ┆           ┆            ┆   ┆          ┆          ┆            ┆ Manufactur │
│        ┆ Stock      ┆           ┆            ┆   ┆          ┆          ┆            ┆ ing        │
│ ACIW   ┆ ACI        ┆ $47.30    ┆ 0.33       ┆ … ┆ null     ┆ 560301   ┆ Technology ┆ Computer   │
│        ┆ Worldwide  ┆           ┆            ┆   ┆          ┆          ┆            ┆ Software:  │
│        ┆ Inc.       ┆           ┆            ┆   ┆          ┆          ┆            ┆ Prepackage │
│        ┆ Common     ┆           ┆            ┆   ┆          ┆          ┆            ┆ d…         │
│        ┆ Stoc…      ┆           ┆            ┆   ┆          ┆          ┆            ┆            │
│ ACLS   ┆ Axcelis    ┆ $63.51    ┆ 3.16       ┆ … ┆ 2000     ┆ 480835   ┆ Technology ┆ Industrial │
│        ┆ Technologi ┆           ┆            ┆   ┆          ┆          ┆            ┆ Machinery/ │
│        ┆ es Inc.    ┆           ┆            ┆   ┆          ┆          ┆            ┆ Component… │
│        ┆ Comm…      ┆           ┆            ┆   ┆          ┆          ┆            ┆            │
│ ACMR   ┆ ACM        ┆ $24.70    ┆ 1.09       ┆ … ┆ 2017     ┆ 1557139  ┆ Technology ┆ Industrial │
│        ┆ Research   ┆           ┆            ┆   ┆          ┆          ┆            ┆ Machinery/ │
│        ┆ Inc. Class ┆           ┆            ┆   ┆          ┆          ┆            ┆ Component… │
│        ┆ A Comm…    ┆           ┆            ┆   ┆          ┆          ┆            ┆            │
└────────┴────────────┴───────────┴────────────┴───┴──────────┴──────────┴────────────┴────────────┘

In [44]:
technology_tickers = [
    "SSNLF", "MU", "WDC", "INTC"
]
df_consumer.filter(pl.col("Symbol").is_in(technology_tickers) | pl.col("Name").str.contains("Samsung"))

shape: (3, 11)
┌────────┬────────────┬───────────┬────────────┬───┬──────────┬──────────┬────────────┬────────────┐
│ Symbol ┆ Name       ┆ Last Sale ┆ Net Change ┆ … ┆ IPO Year ┆ Volume   ┆ Sector     ┆ Industry   │
│ ---    ┆ ---        ┆ ---       ┆ ---        ┆   ┆ ---      ┆ ---      ┆ ---        ┆ ---        │
│ str    ┆ str        ┆ str       ┆ f64        ┆   ┆ i64      ┆ i64      ┆ str        ┆ str        │
╞════════╪════════════╪═══════════╪════════════╪═══╪══════════╪══════════╪════════════╪════════════╡
│ INTC   ┆ Intel Corp ┆ $20.06    ┆ 0.07       ┆ … ┆ null     ┆ 69933311 ┆ Technology ┆ Semiconduc │
│        ┆ oration    ┆           ┆            ┆   ┆          ┆          ┆            ┆ tors       │
│        ┆ Common     ┆           ┆            ┆   ┆          ┆          ┆            ┆            │
│        ┆ Stock      ┆           ┆            ┆   ┆          ┆          ┆            ┆            │
│ MU     ┆ Micron     ┆ $108.56   ┆ 2.27       ┆ … ┆ null     ┆ 20694727 ┆ Technology ┆ Semiconduc │
│        ┆ Technology ┆           ┆            ┆   ┆          ┆          ┆            ┆ tors       │
│        ┆ Inc.       ┆           ┆            ┆   ┆          ┆          ┆            ┆            │
│        ┆ Common …   ┆           ┆            ┆   ┆          ┆          ┆            ┆            │
│ WDC    ┆ Western    ┆ $55.45    ┆ 0.4        ┆ … ┆ null     ┆ 5952136  ┆ Technology ┆ Electronic │
│        ┆ Digital    ┆           ┆            ┆   ┆          ┆          ┆            ┆ Components │
│        ┆ Corporatio ┆           ┆            ┆   ┆          ┆          ┆            ┆            │
│        ┆ n Co…      ┆           ┆            ┆   ┆          ┆          ┆            ┆            │
└────────┴────────────┴───────────┴────────────┴───┴──────────┴──────────┴────────────┴────────────┘

In [46]:
df_consumer.write_csv("data/df_tech.csv")

# df_tmp = pl.read_csv("data/df_90.csv")

In [13]:
df_tmp.head()

shape: (5, 12)
┌────────┬──────────────────┬───────────┬────────────┬───┬────────┬────────┬─────────────────┬─────┐
│ Symbol ┆ Name             ┆ Last Sale ┆ Net Change ┆ … ┆ Volume ┆ Sector ┆ Industry        ┆ id  │
│ ---    ┆ ---              ┆ ---       ┆ ---        ┆   ┆ ---    ┆ ---    ┆ ---             ┆ --- │
│ str    ┆ str              ┆ str       ┆ f64        ┆   ┆ i64    ┆ str    ┆ str             ┆ i64 │
╞════════╪══════════════════╪═══════════╪════════════╪═══╪════════╪════════╪═════════════════╪═════╡
│ AMPY   ┆ Amplify Energy   ┆ $5.74     ┆ -0.03      ┆ … ┆ 69084  ┆ Energy ┆ Oil & Gas       ┆ 1   │
│        ┆ Corp. Common St… ┆           ┆            ┆   ┆        ┆        ┆ Production      ┆     │
│ AMR    ┆ Alpha            ┆ $196.75   ┆ 3.35       ┆ … ┆ 16816  ┆ Energy ┆ Coal Mining     ┆ 2   │
│        ┆ Metallurgical    ┆           ┆            ┆   ┆        ┆        ┆                 ┆     │
│        ┆ Resources …      ┆           ┆            ┆   ┆        ┆        ┆                 ┆     │
│ AR     ┆ Antero Resources ┆ $40.75    ┆ 0.01       ┆ … ┆ 412662 ┆ Energy ┆ Oil & Gas       ┆ 3   │
│        ┆ Corporation C…   ┆           ┆            ┆   ┆        ┆        ┆ Production      ┆     │
│ ARIS   ┆ Aris Water       ┆ $28.87    ┆ 0.02       ┆ … ┆ 35745  ┆ Energy ┆ Oilfield Servic ┆ 4   │
│        ┆ Solutions Inc.   ┆           ┆            ┆   ┆        ┆        ┆ es/Equipment    ┆     │
│        ┆ Clas…            ┆           ┆            ┆   ┆        ┆        ┆                 ┆     │
│ BE     ┆ Bloom Energy     ┆ $25.57    ┆ 0.04       ┆ … ┆ 717752 ┆ Energy ┆ Industrial Mach ┆ 5   │
│        ┆ Corporation      ┆           ┆            ┆   ┆        ┆        ┆ inery/Component ┆     │
│        ┆ Class…           ┆           ┆            ┆   ┆        ┆        ┆ …               ┆     │
└────────┴──────────────────┴───────────┴────────────┴───┴────────┴────────┴─────────────────┴─────┘

In [16]:
tmp1 = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k',]
tmp2 = ['a', 'b', 'c', 'd']

print(list(set(tmp1) - set(tmp2)))

['h', 'i', 'e', 'j', 'k', 'g', 'f']

In [50]:
# update the ticker queue dataframe where symbol not in consumer_tickers
# df_tmp = ticker_queue.with_columns()

# get the list of tickers where download is null
downloaded_tickers = ticker_queue.filter(pl.col("Download_time").is_null(),
                                         ~pl.col("Symbol").is_in(technology_tickers))["Symbol"].to_list()

print(len(downloaded_tickers))
df_tmp_queue = ticker_queue.with_columns(
    pl.when(~pl.col("Symbol").is_in(technology_tickers)).then(True).otherwise(pl.col("Downloaded")).alias("Downloaded"),
    pl.when(~pl.col("Symbol").is_in(technology_tickers),
            pl.col("Download_time").is_null()).then(datetime.now()).otherwise(pl.col("Download_time")).alias("Download_time")
)

df_tmp_queue.filter(pl.col("Downloaded") == False)

524

shape: (3, 4)
┌────────┬───────────────┬────────────┬─────────────────┐
│ Symbol ┆ Download_time ┆ Downloaded ┆ Download_Failed │
│ ---    ┆ ---           ┆ ---        ┆ ---             │
│ str    ┆ datetime[μs]  ┆ bool       ┆ bool            │
╞════════╪═══════════════╪════════════╪═════════════════╡
│ WDC    ┆ null          ┆ false      ┆ false           │
│ INTC   ┆ null          ┆ false      ┆ false           │
│ MU     ┆ null          ┆ false      ┆ false           │
└────────┴───────────────┴────────────┴─────────────────┘

In [51]:
df_tmp_queue.filter(pl.col("Download_time").is_null())

shape: (3, 4)
┌────────┬───────────────┬────────────┬─────────────────┐
│ Symbol ┆ Download_time ┆ Downloaded ┆ Download_Failed │
│ ---    ┆ ---           ┆ ---        ┆ ---             │
│ str    ┆ datetime[μs]  ┆ bool       ┆ bool            │
╞════════╪═══════════════╪════════════╪═════════════════╡
│ WDC    ┆ null          ┆ false      ┆ false           │
│ INTC   ┆ null          ┆ false      ┆ false           │
│ MU     ┆ null          ┆ false      ┆ false           │
└────────┴───────────────┴────────────┴─────────────────┘

In [52]:
# persist the data back to s3
s3io.s3_write_parquet(df=df_tmp_queue, file_path=ticker_queue_table)